version: '3'

services:
  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  web:
    image: nginx:1.19-alpine
    depends_on:
      - php
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
